services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      tags:
        - momo-backend:1.0.0
        - momo-backend:latest
    restart: unless-stopped
    expose:
      - "8081"
    networks:
      - momo-network
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: /api
      tags:
        - momo-frontend:1.0.0
        - momo-frontend:latest
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - momo-network
      - frontend

networks:
  momo-network:
    driver: bridge
    internal: true
  frontend:
    driver: bridge
    internal: true
  backend:
    driver: bridge
    internal: true
