services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8081"
    networks:
      - momo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: /api
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - momo-network

networks:
  momo-network:
    driver: bridge
